#!/usr/bin/env ruby

# A Git repo to store your encrypted signing credentials
git_url("https://github.com/YourGitHubUsername/flappy_guy-signing.git")

# Your app identifier in the Developer Portal
app_identifier(["com.example.flappy_guy"])

# Your Apple Developer Portal username
username("example@example.com")
